### PR TITLE
Wketchum dqmtools

### PR DESCRIPTION
**Pull request by wesketchum**
PR for the standalone DQM tools. Draft until things get more finalized.

### CODE REVIEW

**Comment by wesketchum** [comment]
Needs: https://github.com/DUNE-DAQ/rawdatautils/pull/45

**Comment by bieryAtFnal** [comment]
Suggestions for running the new tool(s) are available in the README for this repo.  Before this PR is merged, those can be found [here](https://github.com/DUNE-DAQ/dqmtools/blob/wketchum_dqmtools/docs/README.md).

**Comment by eflumerf** [comment]
Looking at CMakeLists.txt, Config.cmake.in and the Python files, can we change the dependencies to `rawdatautils`, `detdataformats` and `hdf5libs`? (I'm not sure where h5py comes from...)

**Comment by bieryAtFnal** [comment]
Here the steps that I'm using to test these changes:

```
# log into np04-srv-024
cd $HOME/dunedaq
source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
setup_dbt latest
dbt-create -c -n NAFD23-10-10 10OctDQMTest
cd 10OctDQMTest/sourcecode
git clone https://github.com/DUNE-DAQ/rawdatautils -b wketchum/dqm_tools
git clone https://github.com/DUNE-DAQ/dqmtools -b wketchum_dqmtools
git clone https://github.com/DUNE-DAQ/detchannelmaps -b pd2vd_update
cd ..
dbt-workarea-env
dbt-build -j 12
dbt-workarea-env
cd sourcecode/dqmtools
export HTTPS_PROXY=http://np04-web-proxy.cern.ch:3128
pip install -r requirements.txt
unset HTTPS_PROXY
cd ../../

# log into np04-srv-004
cd $HOME/dunedaq/10OctDQMTest
. ./env.sh
cd /data1
dqm_analyzer.py np02_vd_run022794_0013_dataflow0_datawriter_0_20231010T154646.hdf5

```

**Comment by vitaliyWP** [comment]
> hdf5libs

CMakeLists.txt modified. I think previously it was just copied from rawdatautils when dqmtools became separate package.

**Pull request merged**
